version: 2

project_name: globalfs

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: coordinator
    binary: globalfs-coordinator
    main: ./cmd/coordinator
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

  - id: cli
    binary: globalfs
    main: ./cmd/globalfs
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - id: default
    ids:
      - coordinator
      - cli
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - CHANGELOG.md
      - LICENSE
      - config.example.yaml

checksum:
  name_template: "checksums.txt"

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - "^chore(deps)"
      - "^ci:"
      - Merge pull request
      - Merge branch

release:
  github:
    owner: scttfrdmn
    name: globalfs
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"
  header: |
    ## GlobalFS v{{.Version}}

    See [CHANGELOG.md](https://github.com/scttfrdmn/globalfs/blob/main/CHANGELOG.md)
    for the full list of changes.
  footer: |
    **Full Changelog**: https://github.com/scttfrdmn/globalfs/compare/{{.PreviousTag}}...{{.Tag}}
