// Package metadata defines the Store interface used to persist GlobalFS
// coordinator state — site registry and pending replication jobs — across
// restarts.
//
// Two implementations are provided:
//
//   - [EtcdStore]: production-grade, backed by etcd v3.
//   - [MemoryStore]: in-process, zero-dependency, suitable for testing and
//     single-node deployments that do not need durability.
//
// # Key layout (EtcdStore)
//
// All keys are namespaced under a configurable prefix (default "/globalfs/"):
//
//	{prefix}sites/{name}   → JSON-encoded SiteRecord
//	{prefix}jobs/{id}      → JSON-encoded ReplicationJob
//
// # Watch
//
// [Store.Watch] returns a channel of [WatchEvent] values for keys matching a
// given prefix.  The channel is closed when the supplied context is cancelled.
package metadata

import (
	"context"
	"time"

	"github.com/scttfrdmn/globalfs/pkg/types"
)

// SiteRecord is the persisted representation of a GlobalFS site.
type SiteRecord struct {
	// Name is the unique site identifier.
	Name string `json:"name"`

	// Role is the site's function in the cluster (primary / backup / burst).
	Role types.SiteRole `json:"role"`

	// Status is the last-known operational state.
	Status types.SiteStatus `json:"status"`

	// S3Bucket is the backing object-store bucket.
	S3Bucket string `json:"s3_bucket"`

	// S3Region is the AWS region for the bucket.
	S3Region string `json:"s3_region"`

	// S3Endpoint is an optional custom endpoint (e.g. MinIO).
	S3Endpoint string `json:"s3_endpoint,omitempty"`

	// UpdatedAt is the wall-clock time of the last write.
	UpdatedAt time.Time `json:"updated_at"`
}

// ReplicationJob is the persisted representation of a pending inter-site copy.
//
// IDs are generated by the coordinator and stored deterministically so that
// duplicate enqueues for the same (key, dest) overwrite rather than duplicate.
type ReplicationJob struct {
	// ID is the unique job identifier used as the store key.
	ID string `json:"id"`

	// SourceSite is the name of the site to GET the object from.
	SourceSite string `json:"source_site"`

	// DestSite is the name of the site to PUT the object to.
	DestSite string `json:"dest_site"`

	// Key is the object key.
	Key string `json:"key"`

	// Size is the expected object size in bytes (0 = unknown).
	Size int64 `json:"size"`

	// Priority is reserved for future priority-queue ordering.
	Priority int `json:"priority"`

	// CreatedAt is when the job was persisted.
	CreatedAt time.Time `json:"created_at"`
}

// WatchEventType classifies a store mutation.
type WatchEventType string

const (
	// WatchEventPut is emitted when a key is created or updated.
	WatchEventPut WatchEventType = "put"

	// WatchEventDelete is emitted when a key is deleted.
	WatchEventDelete WatchEventType = "delete"
)

// WatchEvent describes a single mutation observed on a watched key prefix.
type WatchEvent struct {
	// Type is the kind of mutation.
	Type WatchEventType

	// Key is the full store key that changed.
	Key string

	// Value is the new serialised value (nil for delete events).
	Value []byte
}

// Store is the persistence interface for GlobalFS coordinator state.
//
// All methods accept a context; callers should pass contexts with appropriate
// deadlines.  Implementations must be safe for concurrent use.
type Store interface {
	// ── Site registry ─────────────────────────────────────────────────────

	// PutSite creates or updates the record for site.Name.
	PutSite(ctx context.Context, site *SiteRecord) error

	// GetSite returns the record for the named site.
	// Returns an error if no record exists.
	GetSite(ctx context.Context, name string) (*SiteRecord, error)

	// ListSites returns all stored site records in unspecified order.
	ListSites(ctx context.Context) ([]*SiteRecord, error)

	// DeleteSite removes the record for the named site.
	// Deleting a non-existent site is a no-op.
	DeleteSite(ctx context.Context, name string) error

	// ── Replication queue ─────────────────────────────────────────────────

	// PutReplicationJob creates or replaces the job record.
	PutReplicationJob(ctx context.Context, job *ReplicationJob) error

	// GetPendingJobs returns all stored replication jobs.
	GetPendingJobs(ctx context.Context) ([]*ReplicationJob, error)

	// DeleteJob removes the job with the given ID.
	// Deleting a non-existent job is a no-op.
	DeleteJob(ctx context.Context, id string) error

	// ── Watch ─────────────────────────────────────────────────────────────

	// Watch returns a channel of WatchEvents for keys matching the given
	// prefix.  The channel is closed when ctx is cancelled.
	Watch(ctx context.Context, prefix string) (<-chan WatchEvent, error)

	// ── Lifecycle ─────────────────────────────────────────────────────────

	// Close releases all resources held by the store.
	Close() error
}
